# Generated by Django 6.0.2 on 2026-04-24 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='stadium',
            field=models.CharField(default='Main Stadium', max_length=100),
        ),
    ]
