# Generated by Django 6.0.2 on 2026-04-24 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_match_stadium'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchSector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.match')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.sector')),
            ],
        ),
    ]
